### ISSUE TITLE
华为P30 系统10.0 崩溃

### ISSUE THREAD

**Issue by smin9** [sollyu/wechat-scanner#1]
2019-12-23 18:24:20.526 19329-19329/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.qbar.sample, PID: 19329
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.view.View$DeclaredOnClickListener.onClick(View.java:6030)
        at android.view.View.performClick(View.java:7189)
        at android.view.View.performClickInternal(View.java:7163)
        at android.view.View.access$3500(View.java:821)
        at android.view.View$PerformClick.run(View.java:27579)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:6025)
        at android.view.View.performClick(View.java:7189) 
        at android.view.View.performClickInternal(View.java:7163) 
        at android.view.View.access$3500(View.java:821) 
        at android.view.View$PerformClick.run(View.java:27579) 
        at android.os.Handler.handleCallback(Handler.java:888) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8147) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.tencent.qbar.sample-ozH3rJkdkXXBKw75zQRD1A==/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.qbar.sample-ozH3rJkdkXXBKw75zQRD1A==/lib/arm64, /system/lib64, /system/product/lib64, /hw_product/lib64, /system/product/lib64]]] couldn't find "libwechatQrMod.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at com.tencent.qbar.WechatScanner.init(WechatScanner.kt:76)
        at com.tencent.qbar.WechatScanner.init(WechatScanner.kt:60)
        at com.tencent.qbar.WechatScanner.init$default(WechatScanner.kt:59)
        at com.tencent.qbar.sample.MainActivity.onClickInit(MainActivity.kt:36)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.view.View$DeclaredOnClickListener.onClick(View.java:6025) 
        at android.view.View.performClick(View.java:7189) 
        at android.view.View.performClickInternal(View.java:7163) 
        at android.view.View.access$3500(View.java:821) 
        at android.view.View$PerformClick.run(View.java:27579) 
        at android.os.Handler.handleCallback(Handler.java:888) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8147) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by sollyu** [comment]
如果出现`dalvik.system.PathClassLoader`的问题，基本是Android Studio的问题，使用命令行调试即可。
```bash
# Windows
gradlew.bat installDebug
# Linux
./gradlew installDebug
```
