### ISSUE TITLE
各种崩溃

### ISSUE THREAD

**Issue by josephyuen** [sollyu/wechat-scanner#2]
**1---------    Android 10   p20 Pro 初始化后，打开相机崩溃**
                     2019-12-24 09:15:14.567 9018-9018/com.tencent.qbar.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.qbar.sample, PID: 9018
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.view.View$DeclaredOnClickListener.onClick(View.java:6030)
        at android.view.View.performClick(View.java:7189)
        at android.view.View.performClickInternal(View.java:7163)
        at android.view.View.access$3500(View.java:821)
        at android.view.View$PerformClick.run(View.java:27579)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:6025)
        at android.view.View.performClick(View.java:7189) 
        at android.view.View.performClickInternal(View.java:7163) 
        at android.view.View.access$3500(View.java:821) 
        at android.view.View$PerformClick.run(View.java:27579) 
        at android.os.Handler.handleCallback(Handler.java:888) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8147) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
     Caused by: java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:582)
        at android.hardware.Camera.open(Camera.java:401)
        at com.tencent.qbar.sample.MainActivity.onClickOpen(MainActivity.kt:44)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.view.View$DeclaredOnClickListener.onClick(View.java:6025) 
        at android.view.View.performClick(View.java:7189) 
        at android.view.View.performClickInternal(View.java:7163) 
        at android.view.View.access$3500(View.java:821) 
        at android.view.View$PerformClick.run(View.java:27579) 
        at android.os.Handler.handleCallback(Handler.java:888) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8147) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 

**2---------    Android 6.0   魅蓝5s 初始化后，打开相机崩溃，是来自C 层的崩溃**
      
         12-24 09:17:35.374 30066-30066/com.tencent.qbar.sample A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdbc4f000 in tid 30066 (ent.qbar.sample)

**Comment by sollyu** [comment]
问题1：善用搜索引擎，基本权限问题
问题2：暂时未知，确定是这个问题？

**Comment by sollyu** [comment]
刚才测试了Android10，没有问题
